Feature/silicon compatibility
dreipol/dreimultiplatform pull request #29
Opened 2023-05-05 06:50 UTC by lailabecker

2023-05-08 11:39 UTC, melbic requested changes

2023-05-08 11:39 UTC, melbic commented on build.gradle
> -        api "org.reduxkotlin:redux-kotlin-thunk:$versions_redux_kotlin"
Der sollte glaubs drin bleiben, da wir dies brauchen und es noch aktuell ist: https://github.com/reduxkotlin/redux-kotlin-thunk

2023-05-08 11:39 UTC, melbic commented on src/iosMain/kotlin/ch/dreipol/dreimultiplatform/Flow+iOS.kt
> +        onEach: (item: Any?) -> Unit, // The Swift 5.8 compiler cannot compile calls to subscribe if it's generic...
Eigentlich lieber eine zweite subscribe Methode und diese so belassen wie es korrekterweise sein sollte.

2023-05-08 11:39 UTC, melbic commented on src/commonMain/kotlin/org/reduxkotlin/Thunk.kt
> +//fun <State> ThunkMiddleware<State>.withExtraArgument(arg: Any?) = createThunkMiddleware<State>(arg)
Evtl diesen Kommentar entfernen

2023-05-08 11:39 UTC, melbic commented on build.gradle
> -        api("org.reduxkotlin:reselect:$versions_redux_kotlin")
Hier bin ich unschlüssig ob wir zukünftig nicht den Fork hier verwenden sollen, oder sogar diesen selbst forken und einbinden: https://github.com/1gravity/redux-kotlin-select

2023-05-08 11:41 UTC, melbic reviewed
Habe ein paar Kommentare gemacht...

2023-05-08 12:30 UTC, lailabecker commented on build.gradle
> -        api("org.reduxkotlin:reselect:$versions_redux_kotlin")
Wir hatten ja gesagt, dass wir es nicht machen wollen, da der der Fork auch schon seit längerem nicht mehr geupdatet wurde. Und wenn wir es selbst forken, finde ich es einfacher zu maintainen, wenn es im gleichen repo ist 😬

2023-05-09 13:01 UTC, melbic approved these changes

2023-05-09 13:01 UTC, melbic commented on src/iosMain/kotlin/ch/dreipol/dreimultiplatform/Flow+iOS.kt
> +    fun subscribe58(
Ich hätte das eher subscribeAny genannt, aber 58 geht auch.

2023-05-09 13:01 UTC, melbic commented on build.gradle
> -        api("org.reduxkotlin:reselect:$versions_redux_kotlin")
Jein, dafür wenn mal doch noch was passiert im anderen Repo, dann müssen wir es rüber kopieren. Und ist nicht mehr so gut nachvollziehbar. Ich würde aber auf jeden Fall trotzdem die andere Version verwenden ab jetzt, da sind wir zwar nicht mehr komplett kompatibel, aber dafür haben wir Typen und es fühlt sich nicht so zusammengeflickt an.

2023-05-09 13:17 UTC, lailabecker commented on build.gradle
> -        api("org.reduxkotlin:reselect:$versions_redux_kotlin")
Soweit ich sehe, ist das 1gravity package gar nicht mehr gepublished. Von daher haben wir gar keine andere Wahl.

2023-05-09 13:17 UTC, merged